/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './translate.module';
class TranslateModuleInjector extends import0.ɵNgModuleInjector<import1.TranslateModule> {
  _TranslateModule_0:import1.TranslateModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.TranslateModule {
    this._TranslateModule_0 = new import1.TranslateModule();
    return this._TranslateModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.TranslateModule)) { return this._TranslateModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TranslateModuleNgFactory:import0.NgModuleFactory<import1.TranslateModule> = new import0.NgModuleFactory<any>(TranslateModuleInjector,import1.TranslateModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYmVybmFyZC9kZXZlbG9wbWVudC9tb2R1bGVzL2FuZ3VsYXJ0cmFuc2xhdGVjb21wb25lbnQvc3JjL3RyYW5zbGF0ZS5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9iZXJuYXJkL2RldmVsb3BtZW50L21vZHVsZXMvYW5ndWxhcnRyYW5zbGF0ZWNvbXBvbmVudC9zcmMvdHJhbnNsYXRlLm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
