/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './translate.component';
import * as import2 from 'bdt105angulartranslateservice/src/translate.service';
import * as import3 from 'bdt105angulardatabaseservice/src/database.service';
import * as import4 from 'bdt105angularconnexionservice/src/connexion.service';
import * as import5 from './translateoptions.service';
const styles_TranslateComponent:any[] = ([] as any[]);
export const RenderType_TranslateComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TranslateComponent,
  data: {}
}
);
export function View_TranslateComponent_0(l:any):import0.ɵViewDefinition {
    return import0.ɵvid(0,[(l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
  ))],(null as any),(ck,v) => {
    var co:import1.TranslateComponent = v.component;
    const currVal_0:any = co.translation;
    ck(v,0,0,currVal_0);
  });
}
function View_TranslateComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'translate',([] as any[]),(null as any),(null as any),(null as any),View_TranslateComponent_0,RenderType_TranslateComponent)),
    import0.ɵprd(256,(null as any),import2.TranslateService,import2.TranslateService,[
      import3.DatabaseService,
      import4.ConnexionService
    ]
    ),
    import0.ɵdid(57344,(null as any),0,import1.TranslateComponent,[
      import2.TranslateService,
      import5.TranslateOptions
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,2,0);
  },(null as any));
}
export const TranslateComponentNgFactory:import0.ComponentFactory<import1.TranslateComponent> = import0.ɵccf('translate',import1.TranslateComponent,View_TranslateComponent_Host_0,{
  text: 'text',
  isTag: 'isTag'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvYmVybmFyZC9kZXZlbG9wbWVudC9tb2R1bGVzL2FuZ3VsYXJ0cmFuc2xhdGVjb21wb25lbnQvc3JjL3RyYW5zbGF0ZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9iZXJuYXJkL2RldmVsb3BtZW50L21vZHVsZXMvYW5ndWxhcnRyYW5zbGF0ZWNvbXBvbmVudC9zcmMvdHJhbnNsYXRlLmNvbXBvbmVudC50cyIsIm5nOi8vL2hvbWUvYmVybmFyZC9kZXZlbG9wbWVudC9tb2R1bGVzL2FuZ3VsYXJ0cmFuc2xhdGVjb21wb25lbnQvc3JjL3RyYW5zbGF0ZS5jb21wb25lbnQudHMuVHJhbnNsYXRlQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9ob21lL2Jlcm5hcmQvZGV2ZWxvcG1lbnQvbW9kdWxlcy9hbmd1bGFydHJhbnNsYXRlY29tcG9uZW50L3NyYy90cmFuc2xhdGUuY29tcG9uZW50LnRzLlRyYW5zbGF0ZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsInt7dHJhbnNsYXRpb259fSIsIjx0cmFuc2xhdGU+PC90cmFuc2xhdGU+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsyQkNBQTtNQUFBO01BQUE7SUFBQTtFQUFBOztJQUFBO0lBQUE7Ozs7O0lDQUE7Z0JBQUE7OztJQUFBO0lBQUE7Z0JBQUE7OztJQUFBO0tBQUE7OztJQUFBOzs7Ozs7OyJ9
